### ISSUE TITLE
Permission error in keyboard on Mac

### ISSUE THREAD

**Issue by genequ** [glitchassassin/lackey#108]
Thanks for making this happen. 
I got an error when running on Mac:

>>> from lackey import *
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/keyboard/__init__.py", line 138, in listen
    _os_keyboard.listen(self.queue, _key_table.is_allowed)
  File "/usr/local/lib/python2.7/site-packages/keyboard/_darwinkeyboard.py", line 400, in listen
    raise OSError("Error 13 - Must be run as administrator")
OSError: Error 13 - Must be run as administrator

**Comment by glitchassassin** [comment]
This error comes from the underlying [`keyboard`](https://github.com/boppreh/keyboard) module, and is a result of OS X's security restrictions - any application which listens for key presses (which [`keyboard`](https://github.com/boppreh/keyboard) does by default) needs to be run with administrative privileges.

That said, it shouldn't impact any of Lackey's functionality, as we aren't doing any keyboard listening!

Feel free to submit an issue to the [`keyboard` Issues list](https://github.com/boppreh/keyboard/issues) to suggest this be handled more gracefully.

**Comment by glitchassassin** [comment]
Lackey does in fact listen to keypresses for a specific keyboard shortcut, alt+shift+c, which terminates the script. This is a Sikuli feature that Lackey implements for consistency.

However, the import should work fine, aside from displaying that error - you won't be able to use the keyboard shortcut, but as the error happens in a separate thread, the rest of the library should be unaffected.
