### ISSUE TITLE
mouseDown error msg

### ISSUE THREAD

**Issue by howtoesc** [glitchassassin/lackey#115]
When I use mouseDown ,there are error message:

import lackey
lackey.Region(1,1,1,1).mouseDown(lackey.Mouse.LEFT)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 955, in mouseDown
    return PlatformManager.mouseButtonDown(button)
AttributeError: 'PlatformManagerWindows' object has no attribute 'mouseButtonDown'

**Comment by glitchassassin** [comment]
Thanks, don't know how I missed that. Patch is in the develop ring now.
