### ISSUE TITLE
Sample code gives error...

### ISSUE THREAD

**Issue by Moondra** [glitchassassin/lackey#41]
I'm trying the sample code written on the first page and I'm getting the following error.
I'm using Windows 7 and Python 2.7.

Thanks.

Traceback (most recent call last):
  File "C:\Python27\testing_lackey.py", line 6, in <module>
    click("Start_Button.png")
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 552, in click
    target_location = self.find(target).getTarget()
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 374, in find
    match = self.exists(pattern)
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 509, in exists
    pattern = Pattern(pattern)
  File "C:\Python27\lib\site-packages\lackey\RegionMatching.py", line 39, in __init__
    raise OSError("File not found: {}".format(path))
OSError: File not found: Start_Button.png

**Comment by glitchassassin** [comment]
Hi Moondra,

The sample code assumes you have images captured for the script to load. To get these images with Snipping Tool:

* Capture the Start button. Save as "Start_Button.png" in the same directory as your script.
* Capture the Control Panel button in the Start Menu. Save as "Control_Panel.png" in the same directory as your script.
* Capture the icon for Notepad (if it appears in your Start Menu - you can substitute another common app). Save as "Notepad.png" in the same directory as your script.

If you develop automation scripts with the Sikuli IDE, these images will be saved automatically for you with a random number string. This is how I usually develop automation scripts before porting them to Lackey.

Hope this helps!
