### ISSUE TITLE
Error importing from interpreter

### ISSUE THREAD

**Issue by glitchassassin** [glitchassassin/lackey#42]
Calling `import lackey` from the interpreter results in an AttributeError:

    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "lackey\__init__.py", line 24, in <module>
        from .PlatformManagerWindows import PlatformManagerWindows
    File "lackey\PlatformManagerWindows.py", line 16, in <module>
        from .Settings import Debug
    File "lackey\Settings.py", line 126, in <module>
        class SettingsMaster(object):
    File "lackey\Settings.py", line 160, in SettingsMaster
        BundlePath = os.path.dirname(os.path.abspath(os.path.join(os.getcwd(), __main__.__file__)))
    AttributeError: 'module' object has no attribute '__file__'

**Comment by glitchassassin** [comment]
Fixed with version 0.5.2 (just released to Pypi).
